services:
  apply-service:
    image: 'ghcr.io/hacksmc-official/apply-service:latest'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:3000
    networks:
      - hacksmc-network
networks:
  hacksmc-network:
    external: true
